### ISSUE TITLE
SVG export seems to have some trouble

### ISSUE THREAD

**Issue by msurguy** [RPisRyan/fiddlesticks#1]
Hi! Thanks for publishing this repo! 

I'm trying to get the SVG export to work and currently the resulting SVG document is missing its header and the root SVG tag. It instead starts with `g` tag. I'm not very familiar with VS so I don't know where to make the change. 

Perhaps it is as easy as adding one line somewhere.

**Comment by RPisRyan** [comment]
Sorry I never responded to this. This has been fixed.
